### ISSUE TITLE
Ctrl-C exits instead of clearing prompt

### ISSUE THREAD

**Issue by ideasman42** [redox-os/ion#286]
**Reproduction**: Type in one or more  characters, press Ctrl-C.

**Expected behavior**: The text in the prompt should be cleared, but the shell should not exit (Ctrl-D is typically used for this).

Note that while its arguable what should happen in this case, bash/zsh/fish all clear the prompt, and since Ctrl-D key exists for exiting, I think it would be nice to support this behavior too.

**Actual behavior**: `ion: ctrl-c` is printed and ion exits.

**Build information**: Arch Linux

**Comment by chetgurevitch** [comment]
This is known. Signal handling hasn't been implemented yet.

**Comment by MovingtoMars** [comment]
In GNU readline, when a CTRL+C is entered, I believe it returns from the `readline()` function just like liner does.

I'm pretty sure it's the responsibility of the shell to call `readline()` again after receiving `io::ErrorKind::Interrupted`.

**Comment by mmstick** [comment]
This issue is now resolved.

**Comment by z3ntu** [comment]
Actually it's not fixed.
I just installed the newest version, ran `yes` and then Ctrl+C and I landed back in my fish shell. Ctrl+C while no program is running works as intended.

**Comment by mmstick** [comment]
Are you sure you have the latest commit ( 47aa80fd55ad76eac4f42b947ece021e6d26e2db )? Works fine over here.

**Comment by mmstick** [comment]
If you are referring to job control, this is about handling Ctrl+C with the prompt (ie: clearing text). Signal handling is not implemented in the shell, only in liner's read_line function.

**Comment by mmstick** [comment]
Pressing Ctrl+C on the prompt just exits read_line and re-executes read_line to display a new prompt.
