### ISSUE TITLE
All commands cause Ion to be sent to the backgorund

### ISSUE THREAD

**Issue by huntergoldstein** [redox-os/ion#369]
**Reproduction**: Run any non-builtin command inside Ion
**Behavior**: [![asciicast](https://asciinema.org/a/XT7tI7m61169Bqsy60V12e2i9.png)](https://asciinema.org/a/XT7tI7m61169Bqsy60V12e2i9)

**Expected behavior**: [describe the behavior you would expect the repro to yield.]

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].

**Build information**:
- `git rev-parse HEAD`: f5f0b1a25585fa7dc3065e9d6c62a828339d6416

**Comment by mmstick** [comment]
I believe that's because `cargo run` manipulates signals so that the shell process process gets sent into the background rather than ignoring SIGTTOU.

**Comment by huntergoldstein** [comment]
Yup, manually invoking `target/.../ion` will prevent the above from happening. Is there a way to prevent this or do we have to live with it?

**Comment by mmstick** [comment]
I don't really know the specifics as to how `cargo run` is managing it's child processes and their signals, so I'm not sure if we can.

**Comment by mmstick** [comment]
I'm wondering if the shell's PGID is the same as PID when run under `cargo run`.

**Comment by huntergoldstein** [comment]
They are in fact the same when run under cargo run; I'm guessing this makes things trickier?

**Comment by mmstick** [comment]
I've fixed this issue

**Comment by huntergoldstein** [comment]
I'm still seeing this happen on 12caa7b1f64d7b9521c2b7fd891f7a0eb6f52544

**Comment by mmstick** [comment]
The commit that I pushed prior to merging that commit fixed it on my end.

**Comment by huntergoldstein** [comment]
What exactly was the fix? I still can't get it to work.

**Comment by mmstick** [comment]
Having the shell block the SIGTTOU/SIGTTIN/SIGCHLD/SIGSTP signals when it initializes.

**Comment by huntergoldstein** [comment]
Is it possible you have something locally committed or otherwise? I'm still seeing the issue on this machine as well as a separate Ubuntu box.
